'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.296
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("prjTpFinalVB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _01Independent_Projects_03Speech_Bubbles_Bubble() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_01Independent-Projects_03Speech-Bubbles_Bubble", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _120210050849516709419948() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("120210050849516709419948", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1352724383_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1352724383_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3d100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3d100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Application_iphone_HippopoMath_Karabousoft_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Application-iphone-HippopoMath-Karabousoft-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book87() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book87", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bus7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bus7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calcutor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calcutor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fractions2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fractions2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Math2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Math2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menuprincipale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuprincipale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mzl_oseldack_320x480_75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mzl.oseldack.320x480-75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mzl_oseldack1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mzl.oseldack1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reflexion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reflexion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property schoolbus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("schoolbus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property speech_bubble_hi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speech-bubble-hi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_photo_boy_genius_concept_child_with_large_glasses_pencil_and_calculator_102395638() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-photo-boy-genius-concept-child-with-large-glasses-pencil-and-calculator-102"& _ 
                        "395638", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tableau_ecole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tableau_ecole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property téléchargement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("téléchargement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
